# Streamlit Cloud Secrets Configuration
# Add this content to your Streamlit Cloud secrets management
# Go to: https://share.streamlit.io/deploy -> Advanced Settings -> Secrets

[GROQ]
api_key = "your_groq_api_key_here"